### ISSUE TITLE
Import all history from the official repository

### ISSUE THREAD

**Issue by k-takata** [koron/libXpm-win32#4]
libXpm 3.5.11 が出ていますが、[公式のリポジトリ](http://cgit.freedesktop.org/xorg/lib/libXpm)から履歴を全部取り込んでマージするのはどうでしょうか。

手元ではこんな感じになっています。
https://github.com/k-takata/libXpm-win32/tree/topic/merge-upstream

**Comment by koron** [comment]
うーん… なんでぼくはzipから取り込んだんだろうw

**Comment by koron** [comment]
http://cgit.freedesktop.org/xorg/lib/libXpm

から作りなおして、うわがいちゃったほうが良いかもしれないね。

**Comment by k-takata** [comment]
意図的に本家の履歴を取り込まなかったわけではないということなので、PR出しちゃいました。
タグは含まれていないので、必要ならば本家から取ってきてください。

**Comment by k-takata** [comment]
libXpm 3.5.11 に対するパッチとして、こんな感じでどうでしょうか。
https://gist.github.com/k-takata/2b9e7c8d901d7d1da9be

**Comment by koron** [comment]
履歴をちゃんと綺麗にマージするつもりです。

**Comment by koron** [comment]
@k-takata マージしました。テストしてみてもらえますか?

履歴をcherry-pickで作りなおして、master, official ともに以前のものからは pull できなくなってます。
なお古い両ブランチは deprecated/xxx という形で残してありますが、
テストが終わり削除したいと考えています。

**Comment by k-takata** [comment]
ビルド確認できました。問題ありません。

また、deprecated/master と master の差分も確認しましたが、差分は以下の通りで問題ありませんでした。

```diff
diff --git a/autogen.sh b/autogen.sh
old mode 100644
new mode 100755
diff --git a/src/create.c b/src/create.c
index 1e75e55..c0e72db 100644
--- a/src/create.c
+++ b/src/create.c
@@ -347,10 +347,10 @@ SetCloseColor(
 
 	    closenesses[i].cols_index = i;
 	    closenesses[i].closeness =
-		COLOR_FACTOR * (abs((long) col->red - (long) cols[i].red)
-				+ abs((long) col->green - (long) cols[i].green)
-				+ abs((long) col->blue - (long) cols[i].blue))
-		+ BRIGHTNESS_FACTOR * abs(((long) col->red +
+		COLOR_FACTOR * (labs((long) col->red - (long) cols[i].red)
+				+ labs((long) col->green - (long) cols[i].green)
+				+ labs((long) col->blue - (long) cols[i].blue))
+		+ BRIGHTNESS_FACTOR * labs(((long) col->red +
 					   (long) col->green +
 					   (long) col->blue)
 					   - ((long) cols[i].red +
```

autogen.sh のパーミッションは 755 であるべきなので、問題ありません。
create.c の差分も、公式リポジトリに 3.5.11 のあとに加えられた修正 (42ca8d956276bc00bec09e410d76daf053ae35f9) なので問題ありません。

**Comment by koron** [comment]
あ、ごめんなさい。
作業後に 3.5.11 以降の変更もマージしちゃってました。

ということでこのissueは閉じます。
